import type { Metadata } from 'next';
import { IBM_Plex_Mono, Libre_Baskerville, Lora } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';

const libre_baskerville = Libre_Baskerville({
    variable: '--font-libre_baskerville',
    subsets: ['latin'],
    weight: ['400', '700'],
});

const ibm_plex_mono = IBM_Plex_Mono({
    variable: '--font-ibm_plex_mono',
    subsets: ['latin'],
    weight: ['400', '700'],
});
const lora = Lora({
    variable: '--font-lora',
    subsets: ['latin'],
    weight: ['400', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${libre_baskerville.variable} ${ibm_plex_mono.variable} ${lora.variable} antialiased`}
            >
                {children}
                <Toaster />
            </body>
        </html>
    );
}
